### PR TITLE
Add offset to the configuration options

### PR DESCRIPTION
**Pull request by hmens-fa**
Hey, 

Thanks for the awesome plugin, we are very happy with at my company ! We recently updated to version 3 to fix a bug in our software. 

We noticed the offset option was gone. Due to how our web pages are designed we need it (sticky navbars everywhere).

We thought that others might need it also, hence the pull request. 

Let me know what you think !

### CODE REVIEW

**Comment by davist11** [comment]
You can utilize CSS to accomplish offset, which then makes it easier to control with media queries which you can see here http://davist11.github.io/jQuery-One-Page-Nav/top.html

**Comment by HadrienMP** [comment]
Thanks for the tip. Was it the margin: -50px; padding: 50px; that accomplished the offset ?

**Comment by davist11** [comment]
yup, exactly

```
padding-top: 50px;
margin-top: -50px
```

**Comment by HadrienMP** [comment]
Thanks a lot, that will be more useable !

Do you think a "troubleshooting" section in the README would be useful ? (for noobs like me ;) )

**Comment by davist11** [comment]
I assumed the examples were good enough, but I should probably make a note about offset in the README, good suggestion.

**Pull request closed without merging**
