### PR TITLE
Optional scrollOffset

### PR DESCRIPTION
**Pull request by andrearinaldispotsoftware**
There should be the possibility to add extra offset to the scroll. I'd need to skip the height of my top-navbar and I cannot add extra padding/margin-top to my html sections because of other plugins and parallax.

I've been reading of other developers looking for this option. Hope it helps.

### CODE REVIEW

**Comment by aug-riedinger** [comment]
:+1:

**Comment by aug-riedinger** [comment]
Well I'd be in favor of

```
var offset = $(target).offset().top + parseInt($(target).attr('data-offset'));
```

**Comment by aug-riedinger** [comment]
If you want to handle multiple screen sizes, you could allow `data-offset` to be an object in the following form:

```
{
  'default': 50,
  '>800': 70,
  '<1024': 60
}
```

**Comment by davist11** [comment]
This can be easily achieved with CSS, so we will not be adding an offset back to the JS.

**Comment by MickL** [comment]
scrollOffset should still be configurable with java script. Could you please undo the removal? Of course css solution should be prefered but its not really a nice solution for me. There should still be an option to use javascript.

**Comment by andrerinaldi** [comment]
I quote @MickL consideration, but if you guys think that a javascript configuration isn't needed no problem :)

**Comment by davist11** [comment]
How does the CSS solution not work for you?

**Pull request closed without merging**
